/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    HeroSlider: typeof import('./components/Slider/HeroSlider.vue')['default']
    HeroTitle: typeof import('./components/Hero/HeroTitle.vue')['default']
    LocaleSwitcher: typeof import('./components/Generic/LocaleSwitcher.vue')['default']
    LoginForm: typeof import('./components/Form/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./components/Generic/ThemeSwitcher.vue')['default']
  }
}
